# Generated by Django 5.0.6 on 2024-05-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='complete',
            new_name='completed',
        ),
    ]
